### PR TITLE
Support for opentracing 0.32

### PR DESCRIPTION
**Pull request by dougEfresh**

### CODE REVIEW

**Comment by ashishagg** [comment]
Thanks a lot for your contribution.  
Do you want to wait for v0.32.0? We can merge it and release an RC if it is urgent for you.

**Comment by dougEfresh** [comment]
> Thanks a lot for your contribution.
> Do you want to wait for v0.32.0? We can merge it and release an RC if it is urgent for you.

We can wait until 0.32 comes out

**Comment by ashishagg** [comment]
@dougEfresh since 0.32 release is out, can you update the pom with the same? Or let us know we can do that too.

**Comment by ashishagg** [comment]
Closing this PR. We have just migrated to OT v0.33

**Pull request closed without merging**
